export const allSpecies = [
    { commonName: 'Basking Shark', scientificName: 'Cetorhinus maximus' },
    { commonName: 'Beluga Whale', scientificName: 'Delphinapterus leucas' },
    { commonName: 'Bluefin Tuna', scientificName: 'Thunnus thynnus' },
    { commonName: 'Blue Whale', scientificName: 'Balaenoptera musculus' },
    { commonName: 'Bottlenose Dolphin', scientificName: 'Tursiops truncatus' },
    { commonName: 'California Sea Lion', scientificName: 'Zalophus californianus' },
    { commonName: 'Common Seahorse', scientificName: 'Hippocampus kuda' },
    { commonName: 'Dugong', scientificName: 'Dugong dugon' },
    { commonName: 'Elkhorn Coral', scientificName: 'Acropora palmata' },
    { commonName: 'Emperor Penguin', scientificName: 'Aptenodytes forsteri' },
    { commonName: 'Fin Whale', scientificName: 'Balaenoptera physalus' },
    { commonName: 'Giant Clam', scientificName: 'Tridacna gigas' },
    { commonName: 'Giant Manta Ray', scientificName: 'Mobula birostris' },
    { commonName: 'Giant Pacific Octopus', scientificName: 'Enteroctopus dofleini' },
    { commonName: 'Great Hammerhead', scientificName: 'Sphyrna mokarran' },
    { commonName: 'Great White Shark', scientificName: 'Carcharodon carcharias' },
    { commonName: 'Green Sea Turtle', scientificName: 'Chelonia mydas' },
    { commonName: 'Hawksbill Sea Turtle', scientificName: 'Eretmochelys imbricata' },
    { commonName: 'Humpback Whale', scientificName: 'Megaptera novaeangliae' },
    { commonName: 'Leatherback Sea Turtle', scientificName: 'Dermochelys coriacea' },
    { commonName: 'Loggerhead Sea Turtle', scientificName: 'Caretta caretta' },
    { commonName: 'Manatee', scientificName: 'Trichechus manatus' },
    { commonName: 'Moon Jellyfish', scientificName: 'Aurelia aurita' },
    { commonName: 'Narwhal', scientificName: 'Monodon monoceros' },
    { commonName: 'Ocean Sunfish', scientificName: 'Mola mola' },
    { commonName: 'Orca', scientificName: 'Orcinus orca' },
    { commonName: 'Polar Bear', scientificName: 'Ursus maritimus' },
    { commonName: 'Sailfish', scientificName: 'Istiophorus platypterus' },
    { commonName: 'Sea Dragon', scientificName: 'Phycodurus eques' },
    { commonName: 'Sea Otter', scientificName: 'Enhydra lutris' },
    { commonName: 'Sperm Whale', scientificName: 'Physeter macrocephalus' },
    { commonName: 'Tiger Shark', scientificName: 'Galeocerdo cuvier' },
    { commonName: 'Vaquita', scientificName: 'Phocoena sinus' },
    { commonName: 'Walrus', scientificName: 'Odobenus rosmarus' },
    { commonName: 'Whale Shark', scientificName: 'Rhincodon typus' }
].sort((a, b) => a.commonName.localeCompare(b.commonName));
